# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.define "fedmaster" do |fedmaster|
    fedmaster.vm.box = "fedora/28-cloud-base"
    fedmaster.vm.hostname = "fedmaster"
  end

  config.vm.define "fedminion1" do |fedminion1|
    fedminion1.vm.box = "fedora/28-cloud-base"
    fedminion1.vm.hostname = "fedminion1"
  end

  config.vm.define "fedminion2" do |fedminion2|
    fedminion2.vm.box = "fedora/28-cloud-base"
    fedminion2.vm.hostname = "fedminion2"
  end

  config.vm.provider "virtualbox" do |virtualbox, override|
    virtualbox.memory = 2048
    virtualbox.cpus = 2
  end

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    echo '127.0.0.1 localhost' | cat - /etc/hosts > temp && sudo mv temp /etc/hosts
  SHELL

end
